### ISSUE TITLE
Refactor: Remove duplicated web3 terms

### ISSUE THREAD

**Issue by frankiefab100** [Olanetsoft/web3terms#94]
I noticed some web3 terms were repeated. 
Eliminating the first instance should fix this.

See Screenshot:

`L2`
![web3terms-terms-json-GAS FEES](https://user-images.githubusercontent.com/46662771/211908609-18c4afb6-1a34-441e-9beb-6c2c8528c7dc.png)

`node`
![web3terms-terms-json-NODE](https://user-images.githubusercontent.com/46662771/211908617-013690f2-656a-41f9-8566-d367d762ae5f.png)

`gas fees`
![web3terms-terms-json-at-develop-·-frankiefab100-web3terms](https://user-images.githubusercontent.com/46662771/211908625-1478ae79-c9bd-479c-a242-3ce40f49e28d.png)

In the case of `sha256` and `sha-256`. This could be a variance.

![web3terms-terms-json-SHA256](https://user-images.githubusercontent.com/46662771/211909275-198d8a08-64aa-491f-8aad-975be8613036.png)

**Comment by frankiefab100** [comment]
> Thanks for spotting this @frankiefab100 can we work on something to automate this fix?
> 
> @Qudusayo can this be validated with a test case?

Yeah, that's a better solution. But I don't have any idea about it.

**Comment by Qudusayo** [comment]
> Thanks for spotting this @frankiefab100 can we work on something to automate this fix?
> 
> @Qudusayo can this be validated with a test case?

Yes sure, it can. There can be a check in the test to check for repetition according to the term name and prompt the user for a fix if any name is duplicated or there can be another check that automatically removes any duplicate entry found, but I think a check and alert will be better since there's a little difference in the meaning and auto removing a duplicated data based on a duplicated name might not be the best as the automation might know the best one to remove.
